# Generated by Django 4.1.7 on 2023-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="comm/", verbose_name="头像")),
                ("title", models.CharField(max_length=100, verbose_name="用户姓名")),
                ("description", models.CharField(max_length=100, verbose_name="用户简介")),
                ("content", models.TextField(max_length=10000, verbose_name="发布内容")),
                ("vedio_comm", models.FileField(upload_to="vedio/")),
                ("img_comm", models.ImageField(upload_to="image/")),
            ],
            options={"verbose_name": "文化交流", "verbose_name_plural": "文化交流",},
        ),
    ]
