# Generated by Django 4.1.7 on 2023-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comm",
            name="img_comm",
            field=models.ImageField(upload_to="image/", verbose_name="发布图片"),
        ),
        migrations.AlterField(
            model_name="comm",
            name="vedio_comm",
            field=models.FileField(upload_to="vedio/", verbose_name="发布视频"),
        ),
    ]
