"""
Django settings for ggServer project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8*n)jff!)(lbh9&4u0i6vyb&^d&l-ccvuesznp*w!^y8p!9jhm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "import_export",
    "mall",
    "user",
    "cart",
    "charts",
    "comm",
    "order"
]

MIDDLEWARE = [
    # cors
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "ggServer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.media' #add this
            ],
        },
    },
]

WSGI_APPLICATION = "ggServer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mall',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

 # 更改默认语言为中文
LANGUAGE_CODE = 'zh-hans'

 # 更改时区为上海
TIME_ZONE = 'Asia/Shanghai'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"


# # global setting static files
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static\img')

]

MEDIA_URL='/media/'

MEDIA_ROOT=os.path.join(BASE_DIR,'')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS_ORIGIN_ALLOW_ALL access url default false
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
    'http://127.0.0.1:5173',
)

# 导入导出
IMPORT_EXPORT_USE_TRANSACTIONS = True


# 美化admin管理后台,利用simpleUI

# 换成自己Logo链接
SIMPLEUI_LOGO = 'http://127.0.0.1:5173/src/assets/logo.png'

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['商品信息管理','用户管理','购物车管理','交流管理','统计分析','权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '管理用户列表',
                    'icon': 'fa fa-user-secret',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },

        {
            'name': '商品信息管理',
            'icon': 'fa fa-list',
            'models': [
                {
                    'name': '商品列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/mall/goods/',
                    'icon': 'fa fa-bars'
                },
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fa fa-users',
            'models': [
                {
                    'name': '用户信息列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/user/userinfo/',
                    'icon': 'fa fa-user-circle'
                },
                {
                    'name': '用户地址列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/user/address/',
                    'icon': 'fa fa-map-marker-alt'
                },
            ]
        },
        {
            'name': '购物车管理',
            'icon': 'fa fa-shopping-basket',
            'models': [
                {
                    'name': '购物车列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/cart/shoppingcart/',
                    'icon': 'fa fa-shopping-cart'
                },
            ]
        },
        {
            'name': '交流管理',
            'icon': 'fa fa-map',
            'models': [
                {
                    'name': '用户交流信息列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/comm/comm/',
                    'icon': 'fa fa-comment'
                },
            ]
        },
        {
            'name': '统计分析',
            'icon': 'fa fa-signal',
            'models': [
                {
                    'name': '统计分析列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/charts/showcharts/',
                    'icon': 'fa fa-pie-chart'
                },
            ]
        },
    ]
}
