# Generated by Django 4.1.7 on 2023-05-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_alter_userinfo_pwd_alter_userinfo_uname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_trade_num", models.UUIDField()),
                ("order_num", models.CharField(max_length=50)),
                ("trade_no", models.CharField(default="", max_length=120)),
                ("status", models.CharField(default="待支付", max_length=20)),
                ("payway", models.CharField(default="alipay", max_length=20)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.userinfo"
                    ),
                ),
            ],
        ),
    ]
