# Generated by Django 4.1.7 on 2023-03-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showcharts", old_name="title", new_name="chart_url",
        ),
    ]
