# Generated by Django 4.1.7 on 2023-03-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类详情", "verbose_name_plural": "分类详情"},
        ),
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name": "Color", "verbose_name_plural": "Color"},
        ),
        migrations.AlterModelOptions(
            name="goods",
            options={"verbose_name": "商品信息", "verbose_name_plural": "商品信息"},
        ),
        migrations.AlterModelOptions(
            name="goodsdetail",
            options={"verbose_name": "商品详情", "verbose_name_plural": "商品详情"},
        ),
        migrations.AlterModelOptions(
            name="goodsdetailname",
            options={"verbose_name": "商品详情小标题", "verbose_name_plural": "商品详情小标题"},
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name": "Stock", "verbose_name_plural": "Stock"},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name": "SIZE", "verbose_name_plural": "SIZE"},
        ),
    ]
