# Generated by Django 4.1.7 on 2023-03-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0003_alter_goodsdetail_goods_alter_inventory_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsdetail",
            name="gdname",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail_name",
                to="mall.goodsdetailname",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="color",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_color",
                to="mall.color",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_size",
                to="mall.size",
            ),
        ),
    ]
