# Generated by Django 4.1.7 on 2023-03-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0004_alter_goodsdetail_gdname_alter_inventory_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="img",
            field=models.ImageField(default="", upload_to="goods/"),
            preserve_default=False,
        ),
    ]
