# Generated by Django 4.1.7 on 2023-03-21 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="add_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 21, 22, 23, 50, 848709),
                verbose_name="添加时间",
            ),
        ),
    ]
