# Generated by Django 4.1 on 2023-05-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_shoppingcart_add_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="add_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 6, 19, 31, 27, 488243),
                verbose_name="添加时间",
            ),
        ),
    ]
